# Generated by Django 3.2 on 2021-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
