# Generated by Django 3.2.2 on 2021-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_480',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_720',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mv_original',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
