# Generated by Django 3.2.2 on 2021-05-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0003_auto_20210515_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mv_480',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mv_720',
        ),
    ]
